web/config/urls.py
from allauth.account.views import confirm_email
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView, RedirectView
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', RedirectView.as_view(url='yonghun/')),
    path('yonghun/', include('yonghun.urls')),

    ## Authentication
    path('accounts/', include('allauth.urls')),

    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
    path('rest-auth/obtain_token/', obtain_jwt_token),
    path('rest-auth/obtain_refresh/', refresh_jwt_token),

    path('', include('django.contrib.auth.urls')),

]

# urlpatterns += path('accounts/', include('django.contrib.auth.urls')),
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

web/yonghun/profile/urls.py
from django.urls import path

from . import views

app_name = 'profile'

urlpatterns = [
    path("", views.index, name='index'),

]

web/yonghun/models.py
from importlib._common import _

from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.db import models
from django.urls import reverse

from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin, AbstractUser, UserManager

from django.utils import timezone


class UserManager(UserManager):
    def create_superuser(self, *args, **kwargs):
        return super().create_superuser(*args, **kwargs)


class User(AbstractUser):
    email = models.EmailField(unique=True)
    objects = UserManager()  # blank=True: 폼(입력양식)에서 빈채로 저장되는 것을 허용, DB에는 ''로 저장 # CharField 및 TextField는 blank=True만 허용, null=True 허용 X n
    nickname = models.CharField(blank=True, max_length=50)
    introduction = models.TextField(blank=True, max_length=200)
    user_type = models.CharField(blank=True, max_length=40)
    username =models.CharField(unique=False, blank=True, max_length=50)
    # profile_image = models.ImageField(blank=True, null=True)  # null=True: DB에 NULL로 저장

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', ]


class Company(models.Model):
    name = models.CharField(max_length=20, blank=False)
    team = models.CharField(max_length=20, blank=False)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return self.name


class System(models.Model):
    type = models.CharField(max_length=20, blank=False)

    def __str__(self):
        return self.type


class Schedule(models.Model):
    # class Meta:
    #     ordering = ['start_date']
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True, blank=False)
    institution = models.CharField(max_length=100, blank=False, null=True)
    start_date = models.DateField()
    end_date = models.DateField()
    detail = models.CharField(max_length=100, blank=False, null=True)

    def __str__(self):
        return f'[{self.start_date}~{self.end_date}] {self.institution}'


class Inspection(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.SET_NULL, null=True, blank=False)
    system = models.ForeignKey(System, on_delete=models.SET_NULL, null=True, blank=False)
    count = models.IntegerField()

    def __str__(self):
        return f'[{self.schedule.start_date}~{self.schedule.end_date}] {self.schedule.institution} / {self.system}({self.count})'


class BlogType(models.Model):
    name = models.CharField(max_length=20, blank=False)

    def __str__(self):
        return self.name


class Blog(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    # updated_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='blog_update')

    type = models.ForeignKey(BlogType, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=20, blank=False)
    content = models.TextField(max_length=1000000)

    def get_absolute_url(self):
        return reverse('blog:blog-detail', args=[str(self.id)])

web/yonghun/profile/views.py
from django.shortcuts import render

from ..models import Company


def index(request):
    company = Company.objects.all().order_by('start_date')

    context = {'company': company}
    return render(request, 'profile/index.html', context=context)

web/templates/profile/index.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}

<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active" id="home-tab" data-bs-toggle="tab" href="#home" role="tab" aria-controls="home"
           aria-selected="false">경력사항</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="#profile" role="tab" aria-controls="profile"
           aria-selected="false">보유기술</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link" id="contact-tab" data-bs-toggle="tab" href="#contact" role="tab" aria-controls="contact"
           aria-selected="false">자격증</a>
    </li>
</ul>

<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <div class="well" style="margin-top:20px;">
            {% for item in company %}
            <button class="btn " type="button" data-bs-toggle="collapse"
                    data-bs-target="#multiCollapseExample{{forloop.counter}}" aria-expanded="false"
                    aria-controls="multiCollapseExample{{forloop.counter}}">
                {{item.start_date|date:"Y-m-d"}}~{{item.end_date|date:"Y-m-d"}} : {{item.name}}
                <span class="badge badge-primary badge-pill" style="color:blue;">({{item.schedule_set.count}})</span>
            </button>
            {% endfor %}
        </div>
        <div class="row">
            <div class="row">
                {% for item in company %}
                <div class="collapse multi-collapse" id="multiCollapseExample{{forloop.counter}}"
                     style="margin:10px;">
                    <div class="card card-body">
                        <h5>{{item.name}}</h5>
                        <table class="table table-hover table-sm">
                            <thead>
                            <tr>
                                <th>시작일</th>
                                <th>종료일</th>
                                <th>기관명</th>
                                <th>점검대상</th>
                                <th>역할</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for schedule in item.schedule_set.all|dictsort:'start_date' %}
                            <tr>
                                <td>{{schedule.start_date|date:"Y-m-d"}}</td>
                                <td>{{schedule.end_date|date:"Y-m-d"}}</td>
                                <td>***(비공개)***</td>
                                <td>
                                    {% for inspection in schedule.inspection_set.all %}
                                    {{inspection.system}}({{inspection.count}})
                                    {% endfor %}
                                </td>
                                <td>PE</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <div class="well" style="margin-top:20px;">
            <button class="btn " type="button" data-bs-toggle="collapse"
                    data-bs-target="#multiCollapseExample1" aria-expanded="false"
                    aria-controls="multiCollapseExample1">
                모의해킹
            </button>
            <button class="btn " type="button" data-bs-toggle="collapse"
                    data-bs-target="#multiCollapseExample2" aria-expanded="false"
                    aria-controls="multiCollapseExample2">
                웹 사이트 개발
            </button>
            <button class="btn " type="button" data-bs-toggle="collapse"
                    data-bs-target="#multiCollapseExample3" aria-expanded="false"
                    aria-controls="multiCollapseExample3">
                자동화
            </button>
        </div>
        <div class="row">
            <div class="row">
                <div class="collapse multi-collapse" id="multiCollapseExample1"
                     style="margin:10px;">
                    <div class="card card-body">
                        웹 모의해킹
                        모바일 모의해킹
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="collapse multi-collapse" id="multiCollapseExample2"
                    style="margin:10px;">
                    <div class="card card-body">
                        Django + React
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="collapse multi-collapse" id="multiCollapseExample3"
                     style="margin:10px;">
                    <div class="card card-body">
                        업무자동화(한글, 엑셀, PPT, 웹자동화)
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
        <div class="well" style="margin-top:20px;">
            <button class="btn " type="button" data-bs-toggle="collapse"
                    data-bs-target="#multiCollapseExample1" aria-expanded="false"
                    aria-controls="multiCollapseExample1">
                정보처리기사
            </button>
            <button class="btn " type="button" data-bs-toggle="collapse"
                    data-bs-target="#multiCollapseExample2" aria-expanded="false"
                    aria-controls="multiCollapseExample2">
                CISSP
            </button>
            <button class="btn " type="button" data-bs-toggle="collapse"
                    data-bs-target="#multiCollapseExample3" aria-expanded="false"
                    aria-controls="multiCollapseExample3">
                정보보안기사
            </button>
        </div>
        <div class="row">
            <div class="row">
                <div class="collapse multi-collapse" id="multiCollapseExample1"
                     style="margin:10px;">
                    <div class="card">
                        <h5 class="card-header">정보처리기사</h5>
                        <div class="card-body">
                            <h5 class="card-title">주관 : 한국산업인력공단</h5>
                            <h5 class="card-title">취득 : 2018.08</h5>
                            <p class="card-text">데이터베이스, 전자계산기 등</p>
                            <a href="http://www.q-net.or.kr/crf005.do?id=crf00503&jmCd=1320"
                               class="btn btn-primary">정보처리기사</a>
                        </div>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="collapse multi-collapse" id="multiCollapseExample2"
                     style="margin:10px;">
                    <div class="card">
                        <h5 class="card-header">CISSP Associate</h5>
                        <div class="card-body">
                            <h5 class="card-title">주관 : ISC2</h5>
                            <h5 class="card-title">취득 : 2020.10</h5>
                            <p class="card-text">데이터베이스, 전자계산기 등</p>
                            <a href="https://isc2.org/" class="btn btn-primary">ISC2</a>
                            <div data-iframe-width="300" data-iframe-height="300"
                                 data-share-badge-id="c0c3c9be-c3ca-4063-b4e8-a0dc9649b6e3"
                                 data-share-badge-host="https://www.youracclaim.com"></div>
                            <script type="text/javascript" async
                                    src="//cdn.youracclaim.com/assets/utilities/embed.js"></script>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="collapse multi-collapse" id="multiCollapseExample3"
                     style="margin:10px;">
                    <div class="card">
                        <h5 class="card-header">정보보안기사</h5>
                        <div class="card-body">
                            <h5 class="card-title">주관 : 한국인터넷진흥원</h5>
                            <h5 class="card-title">취득 : 2020.12</h5>
                            <p class="card-text"> 정보보호에 대한 지식과 운용 경험을 바탕으로 실무적인 시스템과 서버, 네트워크 장비 및 보안시스템
                                운용을 통해, 보안업무 및 보안정책수립과 보안대책 구현, 정보보호 관련 법규 준수 여부를 판단하는 등의
                                업무 수행</p>
                            <a href="https://kisq.or.kr/main/main.do" class="btn btn-primary">정보보안국가기술자격검정센터</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

<script>var triggerTabList = [].slice.call(document.querySelectorAll('#myTab a'))
triggerTabList.forEach(function (triggerEl) {
  var tabTrigger = new bootstrap.Tab(triggerEl)

  triggerEl.addEventListener('click', function (event) {
    event.preventDefault()
    tabTrigger.show()
  })
})

var collapseElementList = [].slice.call(document.querySelectorAll('.collapse'))
var collapseList = collapseElementList.map(function (collapseEl) {
  return new bootstrap.Collapse(collapseEl)
})


</script>


{% endblock %}