web/config/urls.py
from allauth.account.views import confirm_email
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView, RedirectView
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', RedirectView.as_view(url='yonghun/')),
    path('yonghun/', include('yonghun.urls')),

    ## Authentication
    path('accounts/', include('allauth.urls')),

    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
    path('rest-auth/obtain_token/', obtain_jwt_token),
    path('rest-auth/obtain_refresh/', refresh_jwt_token),

    path('', include('django.contrib.auth.urls')),

]

# urlpatterns += path('accounts/', include('django.contrib.auth.urls')),
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

web/yonghun/blog/urls.py
from django.conf.urls import url
from django.db import router
from django.urls import path, include
from rest_framework import routers

from . import views, BlogSerializer

app_name = 'blog'
router = routers.DefaultRouter()
router.register(r'list', BlogSerializer.BlogViewSet)

urlpatterns = [
    path('', views.index, name='index'),
    # path('list', views.BlogListView.as_view(), name='list'),
    # path("create/", views.BlogCreateView.as_view(), name='create'),
    # path('<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    # path("<int:pk>/update/", views.BlogUpdateView.as_view(), name='update'),
    # path("<int:pk>/delete/", views.BlogDeleteView.as_view(), name='delete'),
    url(r'^', include(router.urls))
    # path("<int:blog_pk>/comment/create", views.BlogCommentCreateView.as_view(), name='comment_create'),



    # url(r'^api/', include(router.urls))
]

web/yonghun/contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path("", views.index, name='index'),

]

web/yonghun/profile/urls.py
from django.urls import path

from . import views

app_name = 'profile'

urlpatterns = [
    path("", views.index, name='index'),

]

web/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"-->
    <!--          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/filter.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>


</head>
<body>

<div class="container-fluid">
    <div class="row" style="height:1em;"></div>
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
            <div class="well">
                <ul class="sidebar-nav">

                    {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>

                    {% endif %}
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'profile:index' %}">Profile</a></li>
                    <li><a href="{% url 'blog:index' %}">Blog</a></li>
                    <li><a href="{% url 'contact:index' %}">Contact</a></li>
                </ul>
            </div>
            {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
</div>
</body>
</html>

web/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Welcome to Yonghun's Home</h1>
  <p>It's all about yonghun<em></em>!</p>
{% endblock %}